networks:
  online-auction:
    driver: bridge
    name: online-auction

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak
    hostname: keycloak
    command: >
      start-dev
      --http-enabled=true
      --http-port=8080
      --hostname=localhost
      --hostname-strict=false
      --import-realm
    ports:
      - "8180:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_PROXY_HEADERS=xforwarded
      - KC_HTTP_RELATIVE_PATH=/
    volumes:
      - ./keycloak/realm-dev.json:/opt/keycloak/data/import/realm-dev.json:ro
    networks:
      - online-auction

  redis:
    image: redis:8-alpine
    hostname: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - online-auction

  postgres:
    image: postgres:15
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: auction_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - online-auction
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./quartz/quartz-schema.sql:/docker-entrypoint-initdb.d/quartz-schema.sql

  mailhog:
    image: mailhog/mailhog:latest
    hostname: mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped
    networks:
      - online-auction

  kafka:
    image: apache/kafka:4.1.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9091,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: CONTROLLER://:9093,INTERNAL://:9091,EXTERNAL://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      CLUSTER_ID: bgwoWzvSSlKmk2ysynPDNg
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_NUM_PARTITIONS: 10
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_COORDINATOR_REBALANCE_PROTOCOLS: "classic,consumer,share"
      KAFKA_UNSTABLE_API_VERSIONS_ENABLE: "true"
      KAFKA_GROUP_SHARE_PARTITION_MAX_RECORD_LOCKS: 100
      TZ: "Asia/Ho_Chi_Minh"
    networks:
      - online-auction
    healthcheck:
      test: /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9091 --list > /dev/null 2>&1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - kafka_data:/var/lib/kafka/data

volumes:
  postgres_data:
  redis_data:
  kafka_data:
