networks:
  online-auction:
    driver: bridge
    name: online-auction

services:
  redis:
    image: redis:8-alpine
    hostname: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - online-auction

  postgres:
    image: postgres:15
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: auction_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - online-auction
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  pgadmin:
#    image: dpage/pgadmin4:latest
#    hostname: pgadmin
#    container_name: pgadmin
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    ports:
#      - "5050:80"
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin
#    networks:
#      - online-auction
#    restart: unless-stopped
#    depends_on:
#      postgres:
#        condition: service_healthy

  mailhog:
    image: mailhog/mailhog:latest
    hostname: mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped
    networks:
      - online-auction

volumes:
  postgres_data:
  redis_data: